# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50, verbose_name='公司名称')),
                ('jobName', models.CharField(max_length=50, verbose_name='职位名称')),
                ('jobInfo', models.TextField(max_length=1000, verbose_name='职位介绍')),
                ('jobNeed', models.TextField(max_length=1000, verbose_name='职位要求')),
                ('pubTime', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('isFullTime', models.BooleanField(default=False, verbose_name='全职')),
                ('isPractice', models.BooleanField(default=False, verbose_name='兼职')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='网址')),
                ('contactEmail', models.CharField(max_length=30, verbose_name='联系人邮箱')),
                ('publisherEmail', models.CharField(max_length=30, verbose_name='发布人邮箱')),
                ('isPublish', models.BooleanField(default=False, verbose_name='发布')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingName', models.CharField(max_length=50, verbose_name='会议名称')),
                ('pubTime', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('startTime', models.DateField(verbose_name='会议开始日期')),
                ('endTime', models.DateField(verbose_name='会议结束日期')),
                ('place', models.CharField(max_length=200, verbose_name='会议地点')),
                ('meetingInfo', models.TextField(max_length=1000, verbose_name='会议信息')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='会议网址')),
                ('isPublish', models.BooleanField(default=False, verbose_name='发布')),
            ],
        ),
    ]
