# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='orderID',
            field=models.IntegerField(default=1, verbose_name='顺序ID'),
            preserve_default=False,
        ),
    ]
