# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20171119_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='annLink',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='详情链接(若无请不填)'),
            preserve_default=False,
        ),
    ]
