# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-15 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20171215_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='annInfo',
            field=models.TextField(max_length=1000, verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobInfo',
            field=models.TextField(max_length=4000, verbose_name='职位介绍'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobNeed',
            field=models.TextField(max_length=4000, verbose_name='职位要求'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingInfo',
            field=models.TextField(max_length=4000, verbose_name='会议信息'),
        ),
    ]
