# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20171215_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestName', models.CharField(max_length=50, verbose_name='竞赛名称')),
                ('contestInfo', models.TextField(max_length=4000, verbose_name='竞赛简介')),
                ('pubTime', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='网址')),
                ('isPublish', models.BooleanField(default=False, verbose_name='发布')),
            ],
        ),
    ]
